name: Portfolio Workflow
run-name: Running formating
on: [push]
jobs:
  formating:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run format:fix
      - run: npm run format
